project_id = "yhpfgxeqghfdbqkhuwep"

[functions.send-purchase-order-email]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = false

[functions.square-create-customer]
verify_jwt = false

[functions.square-charge-subscription]
verify_jwt = false

[functions.send-billing-email]
verify_jwt = false

[functions.check-trial-expiry]
verify_jwt = false

[functions.square-webhook]
verify_jwt = false

[functions.send-partnership-email]
verify_jwt = false

[functions.send-client-notification]
verify_jwt = false

[functions.delete-company-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.delete-company]
verify_jwt = false

[functions.send-client-invoice]
verify_jwt = false

[functions.charge-client-subscription]
verify_jwt = false

[functions.save-client-card]
verify_jwt = false

[functions.save-client-card-direct]
verify_jwt = false

[functions.send-employee-welcome]
verify_jwt = false

[functions.send-time-report-notification]
verify_jwt = false

[functions.send-estimate]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.charge-company-now]
verify_jwt = false
