project_id = "yhpfgxeqghfdbqkhuwep"

[functions.send-purchase-order-email]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = false

[functions.square-create-customer]
verify_jwt = false

[functions.square-charge-subscription]
verify_jwt = false

[functions.send-billing-email]
verify_jwt = false

[functions.check-trial-expiry]
verify_jwt = false

[functions.square-webhook]
verify_jwt = false

[functions.send-partnership-email]
verify_jwt = false